### ISSUE TITLE
stops after 10 account checks ?

### ISSUE THREAD

**Issue by art-iszt** [xCryptic/MegaKeep#1]
stops working after first 10 logins

restarting it, with same account list, it says 'already logged in' for the first account in the list
after that it works up to the 10th account, as before, and stops

tried various account lists with same result

**Comment by xCryptic** [comment]
that's odd. I've got well over 10 accounts and haven't had this issue. however the way I'm doing this is pretty lazy. if an account doesn't log out for whatever reason, it restarts the whole list. I've gone in and changed the process so it'll retry the current account once and skip it if it fails a second time

I'm not sure what's causing your tenth account to not log out correctly the first time, but let me know if it's fixed now

**Comment by xCryptic** [comment]
according to #2 this is fixed
