### ISSUE TITLE
This Doesnt Work Anymore, Mega must of changed something on their end

### ISSUE THREAD

**Issue by Sibbs** [xCryptic/MegaKeep#10]
This Doesnt Work Anymore, Mega must of changed something on their end

megakeep  constantly gets a unable to log out error

**Comment by Fubuchi** [comment]
Did you start the MegaCmdServer yet?

If yes, try to run the bat `mega-login.bat` directly to see what is the result

**Comment by bnsave100** [comment]
> 
> 
> Did you start the MegaCmdServer yet?
> 
> If yes, try to run the bat `mega-login.bat` directly to see what is the result

where this bat file is located ??

**Comment by Fubuchi** [comment]
> where this bat file is located ??

If you install megacmd correctly following their guide here: https://github.com/meganz/MEGAcmd (read the Non-interactively part in the read me).

After adding the necessary directory to `PATH`, you can use the `meg-*` commands in terminal

**Comment by xCryptic** [comment]
@Fubuchi thanks for assisting

it still works fine for me. if you're having problems logging out, try logging out manually via cmd commands (see MEGAcmd's docs for how to do that). or just try reinstalling MEGAcmd completely

**Comment by xCryptic** [comment]
this is probably the same case as #11, see poster's resolution in the comments
