### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by HiToshiNakamoto** [xCryptic/MegaKeep#11]
### Im getting this error plz help i hv alots of ids on stake

![image](https://user-images.githubusercontent.com/76832402/103434474-d53e5680-4c27-11eb-8e6c-58069033fa61.png)

**Comment by xCryptic** [comment]
you'll have to open the mega cmd and try logging out manually. does this happen with every account or just one?

**Comment by HiToshiNakamoto** [comment]
yes learned mega cmd and logged out successfully 
this error caused because i kill unusual services from windows 10 task manager and thus i killed megacmdserver
if someone kill megacmd that runs in the background he need to again open megacmd again with administrative privilege's and start from there
