### ISSUE TITLE
How do set it to run every 2.5 months on its own?

### ISSUE THREAD

**Issue by johnworthley** [xCryptic/MegaKeep#13]

**Comment by Golumpa** [comment]
The simplest way would be to run it via WTS (Windows Task Scheduler)

https://en.m.wikipedia.org/wiki/Windows_Task_Scheduler
https://www.windowscentral.com/how-create-automated-task-using-task-scheduler-windows-10

**Comment by maybecryptic** [comment]
basically what golumpa said. however I'd recommend against leaving a plain text document with your usernames/passwords sitting around on your computer
