### ISSUE TITLE
Does it really works?

### ISSUE THREAD

**Issue by pythonbarath** [xCryptic/MegaKeep#15]
it doesnot login just userintrace alone working.. just tested with fake login and credentials it showing logged in and logged out in that fake credentials ....

**Comment by aphelion1** [comment]
this works but not always you can check security details in your nega account if it worked, also i have troubles, this not always work, just sometimes,  if the app doesn't work with some account it tries login twice, it appears with their details in txt where the app is located, the app obviously needs fixes, also i don't know this is marked as malware
