### ISSUE TITLE
Colon (:) seperator not found

### ISSUE THREAD

**Issue by aphelion1** [xCryptic/MegaKeep#16]
this has a problem when the password includes (:) ,  the program will not know what or where is the separator, i know a way to fix it could be changing the password but, could you add a way to know the difference between the password sign and the separator?

**Comment by aphelion1** [comment]
I found the problem and it's bigger, the app doesn't recognize symbols in passwords like: @#$%, i changed my password without symbols and worked, fix it please

**Comment by maybecryptic** [comment]
all of my passwords have symbols in them
