### ISSUE TITLE
not of use, unfortunately, if no-admin rights on Win10

### ISSUE THREAD

**Issue by art-iszt** [xCryptic/MegaKeep#2]
at first, many thx for kindly fixing ur previous version
very kind of u

however, the current version won't run on a Win10 machine with no-admin rights :
on a college-machine with restricted user rights (no cmd line access, a bulk of ugly useless av crap installed on that vm/thin-client, nor, of course, admin rights granted, etc)

ur neat app won't work (before one could unpack bits & pieces, move them abouts accordingly, to make it work -- for the first 10-Acc's)

it would be very nice indeed, if -- as Win-folks apparently call it in their universe -- there would be a 'portable Version' that would allow for custom install ?
*tia*

**Comment by xCryptic** [comment]
I'm not sure why the app won't run without admin rights anymore. all I did was reorganize the code so it works more efficiently. it may be a windows defender issue though. it does [think the program is a virus](https://www.virustotal.com/gui/file-analysis/ZTA1YmIwM2VjNjI0NTIwNjY1NTI2ZGFiMDgyMTkzZDA6MTU3MzAwODA1OQ==/detection) for whatever reason. I really don't know why this is happening

also this app is portable. there's no installation; all you need is the exe file to run

**Comment by art-iszt** [comment]
at first, thx again for all ur efforts !

what i did : 
#1 dl'd ur win-exe and fired it up
#2 choose an l/p-txt file, accordingly and let it run

got this : 
[04:24:16 ] mega-login.bat was not found, please install it to the default dirctory: 
https://mega.nz/cmd

**Comment by xCryptic** [comment]
the tool utilizes MEGAcmd's bat files. so if they can't be found, they can't be used

are you sure the tools are located in `C:\Users\(Username)\AppData\Local\MEGAcmd`? I know you said you had this working before. but if the program is unable to detect it, then rather it's not there or the program itself doesn't have the permissions to check that directory

**Comment by art-iszt** [comment]
it does work !
thx a ton. it is of great help.

apparently a permission glitch, my end, the other day. solved. and i keep testing ur app.

however, 
there are some accounts tho it logs in but can't log out; it tells logout attempt #xyz ..
and, 
there are some accounts it logs in but hangs -- no further log message displayed.

i can't figure in what the distinctive feature of these accounts might be -- if any at all

**Comment by xCryptic** [comment]
I'm not sure what would be causing specific accounts to not work correctly. try logging into them manually with megacmd and then try logging out. it should provide some kind of error message

since this specific issue has been resolved, I'm closing this issue
