### ISSUE TITLE
Run MegaKeep

### ISSUE THREAD

**Issue by Ecksil** [xCryptic/MegaKeep#4]
Hi!
Thanks for your work!
How can we run the program? I d'ont see any exe...
Otherwhise, how must we complete the txt form?
first line the mega account adress
second line:: user:pass password
?

**Comment by Golumpa** [comment]
Erm...

https://github.com/xCryptic/MegaKeep/releases/tag/v2

**Comment by xCryptic** [comment]
> How can we run the program? I d'ont see any exe...

golumpa posted the exe download location

> Otherwhise, how must we complete the txt form?

your txt file should look something like this

```
email1@email.com:password1
email2@email.com:password2
email3@email.com:password3
```

feel free to reopen the issue if you have any other questions
