### ISSUE TITLE
Command line direct command

### ISSUE THREAD

**Issue by terrypa** [xCryptic/MegaKeep#5]
Hello first i have to thank you for your work on this program,

second is there a way to run this program form the command line with parameters in cmd like:
megakeep "login:password.txt directory" 

so that u can write .bat file and megakeep will run in the background, every now and then and u don't have to press "run" so u can set it in windows auto start and forget about it completely? 
this way if megacmd is also required to run i can write .bat file:

start megacmd
delay
start megakeep "TXT directory"

put it in autostart and forever forget almost :P

**Comment by xCryptic** [comment]
added with #6
